DEF RUBAN_MARIN     EQU $00 ; MARINE_RIBBON
DEF RUBAN_CONTINENT EQU $01 ; LAND_RIBBON
DEF RUBAN_CIEL      EQU $02 ; SKY_RIBBON
DEF RUBAN_PAYS      EQU $03 ; COUNTRY_RIBBON
DEF RUBAN_NATIONAL  EQU $04 ; NATIONAL_RIBBON
DEF RUBAN_TERRE     EQU $05 ; EARTH_RIBBON
DEF RUBAN_MONDE     EQU $06 ; WORLD_RIBBON