DEF MONTAGNARD            EQU $00
DEF SBIRE_AQUA_M          EQU $01 ; TEAM AQUA*
DEF ELEVEUR_PKMN_F        EQU $02 ; \{PKMN} BREEDER
DEF TOPDRESSEUR_M         EQU $03 ; COOLTRAINER♂
DEF ORNITHOLOGUE          EQU $04
DEF COLLEC                EQU $05
DEF SBIRE_AQUA_F          EQU $06 ; TEAM AQUA*
DEF NAGEUR_M              EQU $07 ; SWIMMER♂
DEF SBIRE_MAGMA_M         EQU $08 ; *
DEF EXPERT_M              EQU $09 ; EXPERT
DEF KARATEKA              EQU $0A ; item name
DEF ADMIN_AQUA            EQU $0B ; *
DEF MYSTIMANIAC           EQU $0C
DEF AROMA                 EQU $0D
DEF RUINEMANIAC           EQU $0E
DEF JOURNALISTES          EQU $0F ; *
DEF FLOTTEUR_F            EQU $10 ; TUBER
DEF FLOTTEUR_M            EQU $11 ; TUBER
DEF TOPDRESSEUR_F         EQU $12 ; COOLTRAINER♀
DEF MADEMOISELLE          EQU $13
DEF CANON                 EQU $14
DEF RICHARD               EQU $15
DEF EXPERT_F              EQU $16 ; EXPERT
DEF POKEMANIAC            EQU $17 ; POKéMANIAC
DEF SBIRE_MAGMA_F         EQU $18 ; *
DEF GUITARISTE            EQU $19
DEF SALTIMBANQUE          EQU $1A
DEF CAMPEUR               EQU $1B
DEF PIQUE_NIQUE           EQU $1C
DEF ENTOMOMANIAC          EQU $1D
DEF KINESISTE_M           EQU $1E ; PSYCHIC
DEF KINESISTE_F           EQU $1F ; PSYCHIC
DEF GENTLEMAN             EQU $20
DEF CONSEIL_4_DAMIEN      EQU $21 ; ELITE FOUR*
DEF CONSEIL_4_PHOEBE      EQU $22 ; ELITE FOUR*
DEF CHAMPION_ROXANNE      EQU $23 ; LEADER*
DEF CHAMPION_BASTIEN      EQU $24 ; LEADER*
DEF CHAMPION_TATE_LIZA    EQU $25 ; LEADER*
DEF ELEVE_M               EQU $26 ; SCHOOL KID
DEF ELEVE_F               EQU $27 ; SCHOOL KID
DEF SR_ET_JR              EQU $28 ; SR. AND JR.*
DEF POKEFAN_M             EQU $29 ; POKéFAN
DEF POKEFAN_F             EQU $2A ; POKéFAN
DEF GAMIN                 EQU $2B
DEF CHAMPION              EQU $2C ; *
DEF PECHEUR               EQU $2D
DEF TRIATHLETE_M_VELO     EQU $2E ; TRIATHLETE
DEF TRIATHLETE_F_VELO     EQU $2F ; TRIATHLETE
DEF TRIATHLETE_M_COURSE   EQU $30 ; TRIATHLETE
DEF TRIATHLETE_F_COURSE   EQU $31 ; TRIATHLETE
DEF TRIATHLETE_M_NAGE     EQU $32 ; TRIATHLETE
DEF TRIATHLETE_F_NAGE     EQU $33 ; TRIATHLETE
DEF DRACOLOGUE            EQU $34
DEF NINJA_FAN             EQU $35
DEF COMBATTANTE           EQU $36
DEF SOEUR_PARASOL         EQU $37
DEF NAGEUR_F              EQU $38 ; SWIMMER♀
DEF JUMELLES              EQU $39 ; *
DEF MARIN                 EQU $3A
DEF DRESSEUR_PKMN_TIMMY   EQU $3B ; \{PKMN} TRAINER*
DEF DRESSEUR_PKMN_BRICE_1 EQU $3C ; \{PKMN} TRAINER*
DEF DRESSEUR_PKMN_BRICE_2 EQU $3D ; \{PKMN} TRAINER*
DEF DRESSEUR_PKMN_BRICE_3 EQU $3E ; \{PKMN} TRAINER*
DEF DRESSEUR_PKMN_FLORA_1 EQU $3F ; \{PKMN} TRAINER*
DEF DRESSEUR_PKMN_FLORA_2 EQU $40 ; \{PKMN} TRAINER*
DEF DRESSEUR_PKMN_FLORA_3 EQU $41 ; \{PKMN} TRAINER*
DEF ELEVEUR_PKMN_M        EQU $42 ; \{PKMN} BREEDER
DEF SCOUT                 EQU $43
DEF PKMN_RANGER_M         EQU $44 ; \{PKMN} RANGER
DEF PKMN_RANGER_F         EQU $45 ; \{PKMN} RANGER
DEF MAGMA_LEADER          EQU $46 ; *
DEF FILLETTE              EQU $47
DEF JEUNE_COUPLE          EQU $48 ; *
DEF VIEUX_COUPLE          EQU $49 ; *
DEF FRERE_ET_SOEUR        EQU $4A ; *
DEF DRESSEUR_PKMN_PIERRE  EQU $4B ; *
DEF MENEUSE_CATHY         EQU $4C ; *
DEF MENEUR_TAKIM          EQU $4D
DEF DRESSEUR_PKMN_RED     EQU $4E
DEF DRESSEUR_PKMN_GREEN   EQU $4F
