DEF HIKER        EQU $00
DEF TEAM_AQUA_M  EQU $01 ; TEAM AQUA*
DEF PKMN_BREEDER_F EQU $02 ; \{PKMN} BREEDER
DEF COOLTRAINER_M EQU $03 ; COOLTRAINER♂
DEF BIRD_KEEPER  EQU $04
DEF COLLECTOR    EQU $05
DEF TEAM_AQUA_F  EQU $06 ; TEAM AQUA*
DEF SWIMMER_M    EQU $07 ; SWIMMER♂
DEF TEAM_MAGMA_M EQU $08 ; *
DEF EXPERT_M     EQU $09 ; EXPERT
DEF TC_BLACK_BELT EQU $0A ; item name
DEF AQUA_LEADER  EQU $0B ; *
DEF HEX_MANIAC   EQU $0C
DEF AROMA_LADY   EQU $0D
DEF RUIN_MANIAC  EQU $0E
DEF INTERVIEWER  EQU $0F ; *
DEF TUBER_F      EQU $10 ; TUBER
DEF TUBER_M      EQU $11 ; TUBER
DEF COOLTRAINER_F EQU $12 ; COOLTRAINER♀
DEF LADY         EQU $13
DEF BEAUTY       EQU $14
DEF RICH_BOY     EQU $15
DEF EXPERT_F     EQU $16 ; EXPERT
DEF POKEMANIAC   EQU $17 ; POKéMANIAC
DEF TEAM_MAGMA_F EQU $18 ; *
DEF GUITARIST    EQU $19
DEF KINDLER      EQU $1A
DEF CAMPER       EQU $1B
DEF PICNICKER    EQU $1C
DEF BUG_MANIAC   EQU $1D
DEF PSYCHIC_M    EQU $1E ; PSYCHIC
DEF PSYCHIC_F    EQU $1F ; PSYCHIC
DEF GENTLEMAN    EQU $20
DEF ELITE_FOUR_SIDNEY EQU $21 ; ELITE FOUR*
DEF ELITE_FOUR_PHOEBE EQU $22 ; ELITE FOUR*
DEF LEADER_ROXANNE   EQU $23 ; LEADER*
DEF LEADER_BRAWLY    EQU $24 ; LEADER*
DEF LEADER_TATE_LIZA EQU $25 ; LEADER*
DEF SCHOOL_KID_M EQU $26 ; SCHOOL KID
DEF SCHOOL_KID_F EQU $27 ; SCHOOL KID
DEF SR_AND_JR    EQU $28 ; SR. AND JR.*
DEF POKEFAN_M    EQU $29 ; POKéFAN
DEF POKEFAN_F    EQU $2A ; POKéFAN
DEF YOUNGSTER    EQU $2B
DEF CHAMPION     EQU $2C ; *
DEF FISHERMAN    EQU $2D
DEF TRIATHLETE_M_BIKE EQU $2E ; TRIATHLETE
DEF TRIATHLETE_F_BIKE EQU $2F ; TRIATHLETE
DEF TRIATHLETE_M_RUN  EQU $30 ; TRIATHLETE
DEF TRIATHLETE_F_RUN  EQU $31 ; TRIATHLETE
DEF TRIATHLETE_M_SWIM EQU $32 ; TRIATHLETE
DEF TRIATHLETE_F_SWIM EQU $33 ; TRIATHLETE
DEF DRAGON_TAMER EQU $34
DEF NINJA_BOY    EQU $35
DEF BATTLE_GIRL  EQU $36
DEF PARASOL_LADY EQU $37
DEF SWIMMER_F    EQU $38 ; SWIMMER♀
DEF TWINS        EQU $39 ; *
DEF SAILOR       EQU $3A
DEF PKMN_TRAINER_WALLY     EQU $3B ; \{PKMN} TRAINER*
DEF PKMN_TRAINER_BRENDAN_1 EQU $3C ; \{PKMN} TRAINER*
DEF PKMN_TRAINER_BRENDAN_2 EQU $3D ; \{PKMN} TRAINER*
DEF PKMN_TRAINER_BRENDAN_3 EQU $3E ; \{PKMN} TRAINER*
DEF PKMN_TRAINER_MAY_1     EQU $3F ; \{PKMN} TRAINER*
DEF PKMN_TRAINER_MAY_2     EQU $40 ; \{PKMN} TRAINER*
DEF PKMN_TRAINER_MAY_3     EQU $41 ; \{PKMN} TRAINER*
DEF PKMN_BREEDER_M EQU $42 ; \{PKMN} BREEDER
DEF BUG_CATCHER  EQU $43
DEF PKMN_RANGER_M  EQU $44 ; \{PKMN} RANGER
DEF PKMN_RANGER_F  EQU $45 ; \{PKMN} RANGER
DEF MAGMA_LEADER EQU $46 ; *
DEF LASS         EQU $47
DEF YOUNG_COUPLE EQU $48 ; *
DEF OLD_COUPLE   EQU $49 ; *
DEF SIS_AND_BRO  EQU $4A ; *
DEF POKEMON_TRAINER_STEVEN    EQU $4B ; *
DEF SALON_MAIDEN_ANABEL    EQU $4C ; *
DEF DOME_ACE_TUCKER    EQU $4D
DEF POKEMON_TRAINER_RED    EQU $4E
DEF POKEMON_TRAINER_GREEN    EQU $4F
